version: '3.8'

services:
  redis-master:
    image: bitnami/redis-cluster:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-master
      - REDIS_NODES=redis-master:6379,redis-replica1:6380,redis-replica2:6381,redis-replica3:6382,redis-replica4:6383
    ports:
      - "6379:6379"
    networks:
      - redis-net

  redis-replica1:
    image: bitnami/redis-cluster:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-replica1
      - REDIS_NODES=redis-master:6379,redis-replica1:6380,redis-replica2:6381,redis-replica3:6382,redis-replica4:6383
    ports:
      - "6380:6379"
    networks:
      - redis-net

  redis-replica2:
    image: bitnami/redis-cluster:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-replica2
      - REDIS_NODES=redis-master:6379,redis-replica1:6380,redis-replica2:6381,redis-replica3:6382,redis-replica4:6383
    ports:
      - "6381:6379"
    networks:
      - redis-net

  redis-replica3:
    image: bitnami/redis-cluster:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-replica3
      - REDIS_NODES=redis-master:6379,redis-replica1:6380,redis-replica2:6381,redis-replica3:6382,redis-replica4:6383
    ports:
      - "6382:6379"
    networks:
      - redis-net

  redis-replica4:
    image: bitnami/redis-cluster:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_CLUSTER_ANNOUNCE_IP=redis-replica4
      - REDIS_NODES=redis-master:6379,redis-replica1:6380,redis-replica2:6381,redis-replica3:6382,redis-replica4:6383
    ports:
      - "6383:6379"
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
